import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/global/header";
import Footer from "./components/global/footer";
import { myFont } from "./font";
import AnnouncementBar from "./components/global/announcementBar";
import ReduxProvider from "./redux/provider";
import CartDrawer from "./components/global/cart-drawer";
import FilterDrawer from "./products/components/filter-drawer";
import SearchBar from "./components/global/searchBar";
import { Analytics } from "@vercel/analytics/next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${myFont.variable} antialiased`}>
        <ReduxProvider>
          <AnnouncementBar />
          <Header />
          {children}
          <Footer />
          <CartDrawer />
          <FilterDrawer />
          <SearchBar />
        </ReduxProvider>
        <div className="overlay"></div>
        <Analytics />
      </body>
    </html>
  );
}
