import type { Metadata } from "next";
import localFont from 'next/font/local' 
import "./globals.css";
import Header from "./components/global/header";
import Footer from "./components/global/footer";

export const myFont = localFont({
  src: './fonts/Matter-Light.woff2',
  variable: "--font-myfont",
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${myFont.variable} antialiased`}
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
