import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/global/header";
import Footer from "./components/global/footer";
import { myFont } from "./font";
import AnnouncementBar from "./components/global/announcementBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${myFont.variable} antialiased`}>
        <AnnouncementBar />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
